### ISSUE TITLE
Cannot load prm file in Windows

### ISSUE THREAD

**Issue by tanjinjack** [sam81/pychoacoustics#40]
Hi,

I can't seem to load a prm file again in Windows. Here's the steps to reproduce it.

1. Unzip "pychoacoustics-0.5.10.zip" as downloaded from the website.
2. In command prompt, `python setup.py install`.
3. In command prompt, `python pychoacoustics.pyw`.
4. Click "load prm", and select a previously saved prm file.
5. I get the error below.

> Traceback (most recent call last):
>   File "C:\Users\20185408\surfdrive\Spyder\pychoacoustics-0.5.10_myV2\pychoacoustics\control_window.py", line 4947, in onClickLoadParametersButton
>     self.loadParameters(fName)
>   File "C:\Users\20185408\surfdrive\Spyder\pychoacoustics-0.5.10_myV2\pychoacoustics\control_window.py", line 5187, in loadParameters
>     tmp['b'+str(blockNumber)]['fileChooserCheckBox'].append(strToBoolean(allLines[foo['b'+str(blockNumber)]['startFileChooser']+i].split(':')[2].strip()))
>   File "C:\Users\20185408\surfdrive\Spyder\pychoacoustics-0.5.10_myV2\pychoacoustics\utils_general.py", line 68, in strToBoolean
>     return out
> UnboundLocalError: local variable 'out' referenced before assignment

Here's what I have tried:
1. Uninstall python completely, restart and reinstall it. I still get the same error.
2. Clone the current version on github - that gives me another issue.
3. Run Pychoacoustics in Linux in a VM. **PRM file can be loaded successfully.**

Is this a Windows specific problem? How can I resolve this?

**Comment by sam81** [comment]
thank you for the bug report. Could you tell me the exact version of Python and PyQt you're using on Windows? You can get this info from the "Help" => "About pychoacoustics" window. I'll try to look into this as soon as I can.

**Comment by sam81** [comment]
also could you send me the parameter file you're trying to load and tell me if this is a parameter file for a built-in experiment or a custom experiment that you're programming yourself? One thing to keep in mind if you're building a custom experiment is that if you change the experiment by adding/removing widgets, for example adding a new text field, parameter files saved for previous versions of the experiment will become unreadable.

**Comment by sam81** [comment]
I haven't been able to reproduce this bug using Python 3.7.4 and PyQt 5.13.1 shipped with WinPython 3.7.4.1, I am able to load previously saved .prm files without any issue. There's not much I can do unless you give me more info and/or send me the problematic .prm file. Besides the info I asked in the previous comments the following would be useful:

Is the problem occurring with a specific .prm file or with any .prm file? 
Have you tried saving a different .prm file and re-loading it; does the problem occur in this case?

**Comment by tanjinjack** [comment]
> thank you for the bug report. Could you tell me the exact version of Python and PyQt you're using on Windows? You can get this info from the "Help" => "About pychoacoustics" window. I'll try to look into this as soon as I can.

I am sorry to have taken a while to respond to you. Everything was installed on my work PC and I left it after I posted the issue, not expecting your prompt and helpful responses! 

Here's what I get from the "About pychoacoustics" screen:
`Python 3.7.4 - PyQt 5.9.2 compiled against PyQt 5.9.6, and running with PyQt 5.9.7 on Windows`.

I could try to upgrade PyQt to 5.13.1 but I'll need to figure out how to do it in Anaconda.

I checked also the one in Linux. It's essentially the same version:
`Python 3.7.4 - PyQt 5.9.2 compiled against PyQt 5.9.6, and running with PyQt 5.9.7 on Linux`.

**Comment by tanjinjack** [comment]
I have done a few tests myself, and they can be summarised as below.

The following prm was originally saved in Linux, and can be loaded without problem in Windows - of course file path is wrong but it loaded without throwing an error.

[prm_good.txt](https://github.com/sam81/pychoacoustics/files/3982541/prm_good.txt)
(I need to rename it into .txt file, but Pychoacoustics still has no problem opening it.)

The prm file below is created in Windows, pointing towards essentially the same wav files and throw the aforementioned error:
[prm_bad.txt](https://github.com/sam81/pychoacoustics/files/3982545/prm_bad.txt)

If you compare both files using Meld, the only difference it reports is the file paths of the wav files. Using the two exact same prm files in Linux also gives the same outcome - prm_good is good, prm_bad is bad.

Is there any prm file bundled within the source code that I can try?

To answer your questions more explicitly:
> Is the problem occurring with a specific .prm file or with any .prm file?

Any prm file I created in Windows.

> Have you tried saving a different .prm file and re-loading it; does the problem occur in this case?

This happens with any prm file I tried to save in Windows, but not those I tried to save in Linux.

**Comment by sam81** [comment]
many thanks for the detailed info and the files. I found the issue: the program uses a colon to separate different fields in the file, and gets "confused" by the colon in the Windows file path "C:/etc/...". I'll try to find a fix as soon as I can.

**Comment by tanjinjack** [comment]
> many thanks for the detailed info and the files. I found the issue: the program uses a colon to separate different fields in the file, and gets "confused" by the colon in the Windows file path "C:/etc/...". I'll try to find a fix as soon as I can.

I was just about to write to you on the same discovery. The colon sign is the one that throws the error. My temporary fix now is to rewrite the folder path in the prm file using relative path, e.g. `../../folder/file.wav` and it seems to work fine.

I'll look forward to a permanent fix but for now I can continue using it.

**Comment by sam81** [comment]
I just pushed a fix in master. It solves the issue of reading parameter files with Windows paths containing a colon. It solves the issue for parameter files generated *from now on*; unfortunately however, parameter files generated with previous versions will need a small modification to be read. On lines with file paths, before the "True" or "False" at the end of the line you need to insert a space (with a text editor). For example:

    Pair 1 WAV1: C:/Users/20185408/surfdrive/MATLAB-surfdrive/piano_wav_short/Piano_note88_P284_NP.wav :False

needs to be changed to:

    Pair 1 WAV1: C:/Users/20185408/surfdrive/MATLAB-surfdrive/piano_wav_short/Piano_note88_P284_NP.wav : False

this will make the old param files readable again. Sorry for the inconvenience! Please let me know how you get on with it.
