### ISSUE TITLE
ImportError: cannot import name 'qrc_resources' from 'pychoacoustics' 

### ISSUE THREAD

**Issue by tanjinjack** [sam81/pychoacoustics#41]
Hi,

It appears I cannot run pychoacoustics with the version if I clone from github.

Here's what I did:
1. Unzip "pychoacoustics-master.zip" as downloaded from Github.
2. In command prompt, `python setup.py install`.
3. In command prompt, `python pychoacoustics.pyw`.
4. I get an error as written below:
> Traceback (most recent call last):
>   File "pychoacoustics.pyw", line 38, in <module>
>     from pychoacoustics import qrc_resources
> ImportError: cannot import name 'qrc_resources' from 'pychoacoustics' (C:\Users\20185408\surfdrive\Spyder\pychoacoustics-master\pychoacoustics\__init__.py)

I tried to compile the qrc resources myself and did the following steps:
1. To compile, I use:
`pyrcc5 -o qrc_resources.py resources.qrc`
2. I copied qrc_resources.py to <pychoacousticsfolder>/build/lib/pychoacoustics/ 
3. Rerun `python setup.py install`.
4. I get the same error.

How can I get this fixed?

**Comment by sam81** [comment]
thank you for the bug report. Please let me know the python and PyQt version you're using. Note that you don't need to run "python setup.py install". You can run pychoacoustics "in place", from the terminal a command like 
    
    /Path/to/python.exe "C:\Users\audiolab\Desktop\pychoacoustics-pyside-0.2.81\pychoacoustics.pyw"

where `/Path/to/python.exe` is the path to your python interpreter, and the second part is the path to where you have unzipped the pychoacoustics source folder.

**Comment by sam81** [comment]
the 'qrc_resources.py' file needs to end up in the 'pychoacoustics' subfolder, so you need to either run:

    pyrcc5 -o pychoacoustics/qrc_resources.py resources.qrc

or run the command as you did before and then move the file to the  'pychoacoustics' subfolder. Please let me know if this works.

**Comment by tanjinjack** [comment]
> the 'qrc_resources.py' file needs to end up in the 'pychoacoustics' subfolder, so you need to either run:
> 
> ```
> pyrcc5 -o pychoacoustics/qrc_resources.py resources.qrc
> ```
> 
> or run the command as you did before and then move the file to the 'pychoacoustics' subfolder. Please let me know if this works.

This works. Thank you very much.
